### ISSUE TITLE
Problema de sincronização da comunicação entre primário e réplicas

### ISSUE THREAD

**Issue by Di-Ca-N** [Di-Ca-N/dropbox#18]
Encontrei um bug com a implementação atual do mecanismo de réplicas. Quando o primário morre, às vezes o novo primário e a réplica ficam dessincronizados na comunicação, fazendo um deles enviar um tipo de mensagem não esperado, o que trava a comunicação a partir desse ponto. 

Não consegui encontrar a raiz do problema, mas suspeito que isso ocorre pela forma como o ReplicaConnection interage com o ReplicaThread, já que uma parte dos comandos é executada no Connection e outra no Thread. Sendo assim, acho que seria melhor passar todo o fluxo de comunicação para dentro do ReplicaThread, para simplificar o fluxo de comunicação e deixá-lo centralizado, a fim de evitar fluxos de comunicação parcialmente realizados.

**Comment by albertoborsatto** [comment]
No caso passar os métodos de autenticação, envio do tipo de update e inicialização da réplica pra dentro de ReplicaThread?

**Comment by albertoborsatto** [comment]
Notei que na main, por algum motivo, quando uma réplica morre, entra duas vezes no exception de handleReplica, porque printa duas vezes. Consequentemente ela chama duas vezes o método de excluir a réplica que morreu (tanto do primário, quanto das outras réplicas). Talvez esse erro de mensagem inesperada esteja vindo disso, mas não tenho certeza. Mas não sei por que ta executando duas vezes...

**Comment by felipe-gallois** [comment]
@Di-Ca-N essa issue ainda deve ficar aberta, ou já foi resolvida?

**Comment by Di-Ca-N** [comment]
O problema foi resolvido, então já podemos fechar a issue.
